// Writes F1R3Pix/vectors/pix-vectors.json from the JavaScript implementation.
// The Rust tests (crates/games/tests/pix.rs, crates/wallet/tests/envelope.rs)
// and the JavaScript tests hold every implementation to these values.
import { writeFileSync } from "node:fs";
import { secp256k1 } from "@noble/curves/secp256k1";
import { bytesToHex, hexToBytes } from "@noble/hashes/utils";
import { idxToCell, radiusFor, cellsFor } from "../src/core/hex.js";
import { seatStart, randomSeat } from "../src/core/seating.js";
import { encodeBody, encodePreview, toHex } from "../src/core/history.js";
import { seal } from "../src/core/envelope.js";

const key = (n) => hexToBytes(n.toString(16).padStart(64, "0"));
const pub = (sk) => bytesToHex(secp256k1.getPublicKey(sk, false));
const INSTANCE = "9f2c4e7a1b3d5f60718293a4b5c6d7e8f9011223344556677889900aabbccdd";
const ADDR = ["1111aqq7mDkxjtYmLanT2sPVZ67HcmhMdBwr8wjAhE2B4kVRxJHM7", "1111bJHrH7cK3m8hW4eTyQWU2RjsX8JmGqYbUvVrV7eYV3kNqMPa", "1111cPs1DgpVHU8bwXzvR4gG8tRxE4oD6NQ2c8SxbfTjK9uWzM2E"];

const spiral = Array.from({ length: cellsFor(12) }, (_, i) => idxToCell(i));
const radius = Object.fromEntries([7, 8, 19, 20, 37, 61, 62, 91, 331, 469].map((c) => [c, radiusFor(c)]));
const seats = ADDR.map((a) => ({ instance: INSTANCE, address: a, start: seatStart(INSTANCE, a) }));
const taken = new Set(["0,0", "-1,1", "0,1"]);
const random = ADDR.map((a) => ({ address: a, radius: 2, taken: [...taken], cell: randomSeat(INSTANCE, a, 2, taken) }));

const paints = [
  { h: 10, owner: ADDR[0], q: 0, r: 0, colour: "#F3D630" },
  { h: 10, owner: ADDR[1], q: -1, r: 1, colour: "#3FA9F5" },
  { h: 12, owner: ADDR[0], q: 0, r: 0, colour: "#E5383B" },
  { h: 15, owner: ADDR[2], q: 1, r: -1, colour: "#3FA9F5" },
];
const body = toHex(encodeBody({ radius: 2, from: 10, to: 16, paints }));
const cells = new Map([["0,0", "#E5383B"], ["-1,1", "#3FA9F5"], ["1,-1", "#3FA9F5"], ["0,1", null]]);
const preview = encodePreview(2, cells);

const alice = key(0xa11ce), bob = key(0xb0b), carol = key(0xca201);
const envelope = toHex(seal(
  { game: "f1r3pix", instance: INSTANCE, sender: { address: ADDR[0], pk: pub(alice) },
    recipients: [{ address: ADDR[1], pk: pub(bob) }, { address: ADDR[2], pk: pub(carol) }], text: "five each if you all turn blue 🔵" },
  { ephemeral: key(0xe9e), contentKey: key(0xc0ffee), n0: hexToBytes("000102030405060708090a0b"),
    nonces: [hexToBytes("101112131415161718191a1b"), hexToBytes("202122232425262728292a2b"), hexToBytes("303132333435363738393a3b")] },
));

const out = {
  note: "Generated by F1R3Pix/client/scripts/make-vectors.mjs; do not edit by hand.",
  spiral, radius, seats, random,
  body: { radius: 2, from: 10, to: 16, paints, hex: body },
  preview: { radius: 2, cells: [...cells], ...preview },
  envelope: {
    game: "f1r3pix", instance: INSTANCE, sender: ADDR[0], text: "five each if you all turn blue 🔵", hex: envelope,
    keys: { [ADDR[0]]: bytesToHex(alice), [ADDR[1]]: bytesToHex(bob), [ADDR[2]]: bytesToHex(carol) },
    publicKeys: { [ADDR[0]]: pub(alice), [ADDR[1]]: pub(bob), [ADDR[2]]: pub(carol) },
  },
};
writeFileSync(new URL("../../vectors/pix-vectors.json", import.meta.url), JSON.stringify(out, null, 1) + "\n");
console.log("wrote vectors/pix-vectors.json");
