[package]
name = "skein-engine"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
skein-core = { path = "../skein-core" }
skein-proto = { path = "../skein-proto" }
skein-spigot = { path = "../skein-spigot" }
