/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const activeAddress: () => [number, number, number, number];
export const activePublicKey: () => [number, number, number, number];
export const allowances: () => [number, number, number, number];
export const contactsDecrypt: (a: number, b: number) => [number, number, number, number];
export const contactsEncrypt: (a: number, b: number) => [number, number, number, number];
export const contactsImport: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number, number, number];
export const createKey: (a: number, b: number) => [number, number, number, number];
export const createKeystore: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number, number, number];
export const enrolPasskey: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const exportKeyFile: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const grantAllowance: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
export const importKeyFile: (a: number, b: number, c: number, d: number) => [number, number, number, number];
export const importKeystore: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number) => [number, number, number, number];
export const invitationInstance: (a: number, b: number) => [number, number, number, number];
export const isAddress: (a: number, b: number) => number;
export const isUnlocked: () => number;
export const keystoreJson: () => [number, number, number, number];
export const listKeys: () => [number, number, number, number];
export const lock: () => [number, number];
export const newInvitation: (a: number, b: number, c: number, d: number) => [number, number];
export const openEnvelope: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number, number, number];
export const openKeystore: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const passkeys: () => [number, number, number, number];
export const redeemInvitation: (a: number, b: number) => [number, number, number, number];
export const registerGameTemplate: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
export const review: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number) => [number, number, number, number];
export const setActive: (a: number, b: number) => [number, number];
export const sign: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => [number, number, number, number];
export const unlockWithPasskey: (a: number, b: number, c: number, d: number) => [number, number];
export const unlockWithPassphrase: (a: number, b: number) => [number, number];
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __externref_drop_slice: (a: number, b: number) => void;
export const __wbindgen_start: () => void;
